import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { root } from './lib.mjs';
const plugin = join(root, 'plugins/caveman');
const manifest = JSON.parse(await readFile(join(plugin, '.codex-plugin/plugin.json'), 'utf8'));
const marketplace = JSON.parse(await readFile(join(root, '.agents/plugins/marketplace.json'), 'utf8'));
const hooks = JSON.parse(await readFile(join(plugin, 'hooks/hooks.json'), 'utf8'));
const parity = JSON.parse(await readFile(join(plugin, 'PARITY.json'), 'utf8'));
const required = ['caveman', 'caveman-commit', 'caveman-review', 'caveman-help', 'caveman-stats', 'caveman-compress', 'cavecrew', 'caveman-init', 'caveman-migrate'];
if (manifest.name !== 'caveman' || manifest.version !== '1.0.0' || manifest.skills !== './skills/' || manifest.hooks !== './hooks/hooks.json') throw new Error('invalid plugin manifest');
if (marketplace.name !== 'thinkhome-caveman' || marketplace.plugins?.[0]?.source?.path !== './plugins/caveman') throw new Error('invalid marketplace');
for (const event of ['SessionStart', 'UserPromptSubmit', 'SubagentStart']) if (!hooks.hooks?.[event]?.[0]?.hooks?.[0]?.commandWindows) throw new Error(`missing cross-platform ${event} hook`);
for (const skill of required) await readFile(join(plugin, 'skills', skill, 'SKILL.md'), 'utf8');
if (parity.upstream?.tag !== 'v1.9.1' || parity.skills.length !== 7 || !parity.mcpShrink) throw new Error('invalid parity report');
console.log(`plugin valid: ${required.length} skills`);
